name: ps_doc
channels:
  - conda-forge
dependencies:
  - gdal>=2.4
  - python>=3.11
  - matplotlib
  - numpy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-bibtex>=2.2
  - sphinxcontrib-svg2pdfconverter
  - cairosvg
  - sphinx-autodoc-typehints
